apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: deny-bash-access
  namespace: default
spec:
  severity: 5
  selector:
    matchLabels:
      app: wisecow
  process:
    matchPaths:
    - path: /bin/bash
  action: Block
